# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - labvolt_arm_controller

  labvolt_arm_controller:
    type: FollowJointTrajectory
    joints:
      - Revolute 1
      - Revolute 2
      - Revolute 3
      - Revolute 4
      - Revolute 5
    action_ns: follow_joint_trajectory
    default: true